raw: /Volumes/Elements/fannie_mae_data/raw/
interim: /Volumes/Elements/fannie_mae_data/interim/
processed: /Volumes/Elements/fannie_mae_data/processed/
outputs: /Volumes/Elements/fannie_mae_data/outputs/
metadata: /Volumes/Elements/fannie_mae_data/metadata/crt-file-layout-and-glossary.xlsx